/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceHistoryRouteImport } from './routes/service-history'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GarageIndexRouteImport } from './routes/garage.index'
import { Route as GarageVehicleIdRouteImport } from './routes/garage.$vehicleId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceHistoryRoute = ServiceHistoryRouteImport.update({
  id: '/service-history',
  path: '/service-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageIndexRoute = GarageIndexRouteImport.update({
  id: '/garage/',
  path: '/garage/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageVehicleIdRoute = GarageVehicleIdRouteImport.update({
  id: '/garage/$vehicleId',
  path: '/garage/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plan': typeof PlanRoute
  '/service-history': typeof ServiceHistoryRoute
  '/settings': typeof SettingsRoute
  '/garage/$vehicleId': typeof GarageVehicleIdRoute
  '/garage/': typeof GarageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plan': typeof PlanRoute
  '/service-history': typeof ServiceHistoryRoute
  '/settings': typeof SettingsRoute
  '/garage/$vehicleId': typeof GarageVehicleIdRoute
  '/garage': typeof GarageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plan': typeof PlanRoute
  '/service-history': typeof ServiceHistoryRoute
  '/settings': typeof SettingsRoute
  '/garage/$vehicleId': typeof GarageVehicleIdRoute
  '/garage/': typeof GarageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plan'
    | '/service-history'
    | '/settings'
    | '/garage/$vehicleId'
    | '/garage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plan'
    | '/service-history'
    | '/settings'
    | '/garage/$vehicleId'
    | '/garage'
  id:
    | '__root__'
    | '/'
    | '/plan'
    | '/service-history'
    | '/settings'
    | '/garage/$vehicleId'
    | '/garage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanRoute: typeof PlanRoute
  ServiceHistoryRoute: typeof ServiceHistoryRoute
  SettingsRoute: typeof SettingsRoute
  GarageVehicleIdRoute: typeof GarageVehicleIdRoute
  GarageIndexRoute: typeof GarageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-history': {
      id: '/service-history'
      path: '/service-history'
      fullPath: '/service-history'
      preLoaderRoute: typeof ServiceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/': {
      id: '/garage/'
      path: '/garage'
      fullPath: '/garage/'
      preLoaderRoute: typeof GarageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/$vehicleId': {
      id: '/garage/$vehicleId'
      path: '/garage/$vehicleId'
      fullPath: '/garage/$vehicleId'
      preLoaderRoute: typeof GarageVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanRoute: PlanRoute,
  ServiceHistoryRoute: ServiceHistoryRoute,
  SettingsRoute: SettingsRoute,
  GarageVehicleIdRoute: GarageVehicleIdRoute,
  GarageIndexRoute: GarageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
