/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedServiceHistoryRouteImport } from './routes/_authenticated/service-history'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedGarageIndexRouteImport } from './routes/_authenticated/garage.index'
import { Route as AuthenticatedGarageVehicleIdRouteImport } from './routes/_authenticated/garage.$vehicleId'
import { Route as PrintTypeVehicleIdRouteImport } from './routes/print.$type.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiceHistoryRoute =
  AuthenticatedServiceHistoryRouteImport.update({
    id: '/service-history',
    path: '/service-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGarageIndexRoute =
  AuthenticatedGarageIndexRouteImport.update({
    id: '/garage/',
    path: '/garage/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGarageVehicleIdRoute =
  AuthenticatedGarageVehicleIdRouteImport.update({
    id: '/garage/$vehicleId',
    path: '/garage/$vehicleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PrintTypeVehicleIdRoute = PrintTypeVehicleIdRouteImport.update({
  id: '/print/$type/$vehicleId',
  path: '/print/$type/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/service-history': typeof AuthenticatedServiceHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/garage/$vehicleId': typeof AuthenticatedGarageVehicleIdRoute
  '/print/$type/$vehicleId': typeof PrintTypeVehicleIdRoute
  '/garage/': typeof AuthenticatedGarageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/service-history': typeof AuthenticatedServiceHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/garage/$vehicleId': typeof AuthenticatedGarageVehicleIdRoute
  '/print/$type/$vehicleId': typeof PrintTypeVehicleIdRoute
  '/garage': typeof AuthenticatedGarageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/service-history': typeof AuthenticatedServiceHistoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/garage/$vehicleId': typeof AuthenticatedGarageVehicleIdRoute
  '/print/$type/$vehicleId': typeof PrintTypeVehicleIdRoute
  '/_authenticated/garage/': typeof AuthenticatedGarageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plan'
    | '/service-history'
    | '/settings'
    | '/garage/$vehicleId'
    | '/print/$type/$vehicleId'
    | '/garage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plan'
    | '/service-history'
    | '/settings'
    | '/garage/$vehicleId'
    | '/print/$type/$vehicleId'
    | '/garage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/plan'
    | '/_authenticated/service-history'
    | '/_authenticated/settings'
    | '/_authenticated/garage/$vehicleId'
    | '/print/$type/$vehicleId'
    | '/_authenticated/garage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrintTypeVehicleIdRoute: typeof PrintTypeVehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-history': {
      id: '/_authenticated/service-history'
      path: '/service-history'
      fullPath: '/service-history'
      preLoaderRoute: typeof AuthenticatedServiceHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garage/': {
      id: '/_authenticated/garage/'
      path: '/garage'
      fullPath: '/garage/'
      preLoaderRoute: typeof AuthenticatedGarageIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garage/$vehicleId': {
      id: '/_authenticated/garage/$vehicleId'
      path: '/garage/$vehicleId'
      fullPath: '/garage/$vehicleId'
      preLoaderRoute: typeof AuthenticatedGarageVehicleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/print/$type/$vehicleId': {
      id: '/print/$type/$vehicleId'
      path: '/print/$type/$vehicleId'
      fullPath: '/print/$type/$vehicleId'
      preLoaderRoute: typeof PrintTypeVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedServiceHistoryRoute: typeof AuthenticatedServiceHistoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedGarageVehicleIdRoute: typeof AuthenticatedGarageVehicleIdRoute
  AuthenticatedGarageIndexRoute: typeof AuthenticatedGarageIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedServiceHistoryRoute: AuthenticatedServiceHistoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedGarageVehicleIdRoute: AuthenticatedGarageVehicleIdRoute,
  AuthenticatedGarageIndexRoute: AuthenticatedGarageIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrintTypeVehicleIdRoute: PrintTypeVehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
